(cl:defpackage vitaslam-msg
  (:use )
  (:export
   "<COMBINEDTEMPLATEMESSAGE>"
   "COMBINEDTEMPLATEMESSAGE"
   "<TOPOLOGICALACTION>"
   "TOPOLOGICALACTION"
   "<TOPOLOGICALEDGE>"
   "TOPOLOGICALEDGE"
   "<TOPOLOGICALMAP>"
   "TOPOLOGICALMAP"
   "<TOPOLOGICALNODE>"
   "TOPOLOGICALNODE"
  ))

